// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhy4XSkOvVmhl8njKmeUhz9p5bkZVx6Rk',
    appId: '1:375829532366:web:878df0341d6e19d9d7ca9f',
    messagingSenderId: '375829532366',
    projectId: 'thecrohns-2466d',
    authDomain: 'thecrohns-2466d.firebaseapp.com',
    storageBucket: 'thecrohns-2466d.appspot.com',
    measurementId: 'G-P0BKNSQSCE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0Sc5_hbiNgO4925iRbd-RlT8_HvxIAwY',
    appId: '1:375829532366:android:8c7d1acd7020370fd7ca9f',
    messagingSenderId: '375829532366',
    projectId: 'thecrohns-2466d',
    storageBucket: 'thecrohns-2466d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTImuVU2yxcC1cTEkySlotdKA3NMZPFOE',
    appId: '1:375829532366:ios:c72702009e631fecd7ca9f',
    messagingSenderId: '375829532366',
    projectId: 'thecrohns-2466d',
    storageBucket: 'thecrohns-2466d.appspot.com',
    iosClientId: '375829532366-5ekbe2n1d22nesoguencq74mp60f4t53.apps.googleusercontent.com',
    iosBundleId: 'com.example.thecrohns',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTImuVU2yxcC1cTEkySlotdKA3NMZPFOE',
    appId: '1:375829532366:ios:c72702009e631fecd7ca9f',
    messagingSenderId: '375829532366',
    projectId: 'thecrohns-2466d',
    storageBucket: 'thecrohns-2466d.appspot.com',
    iosClientId: '375829532366-5ekbe2n1d22nesoguencq74mp60f4t53.apps.googleusercontent.com',
    iosBundleId: 'com.example.thecrohns',
  );
}
